version: '3'
services:
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: sweaterpostgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: qwerty
#      POSTGRES_DB: sweater_db
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  # adminer:
  #     image: adminer
  #     container_name: sweateradminer
  #     restart: always
  #     ports:
  #       - 8081:8080
